### ISSUE TITLE
Permission to submit preprint

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#145]
I think we're basically ready to submit the preprint (and to Gigascience), so I need express permission from all authors to do this. 

Can all authors please comment on this thread with a "I give permission to submit" below, please? I have attached the latest draft for your convenience.

I also need permission from the Genomics England review board, which I will add in due course.

@eric-czech
@timothymillar
@tomwhite
@benjeffery
@alimanfoo
@stallmanGEL
@ravwojdyla
@shz9
@hammer
@jeromekelleher

[vcf-zarr-paper_2024-06-07.pdf](https://github.com/user-attachments/files/15741056/vcf-zarr-paper_2024-06-07.pdf)

**Comment by hammer** [comment]
I give permission to submit

**Comment by tomwhite** [comment]
I give permission to submit

**Comment by eric-czech** [comment]
I give permission to submit

**Comment by stallmanGEL** [comment]
I give permission to submit

***@***.***<http://genomicsresearchsummit.co.uk/>
Samuel Tallman​​​​
Genomics Data Scientist ‑ Research Services
w: www.genomicsengland.co.uk<https://www.genomicsengland.co.uk/>
[Twitter]<https://twitter.com/genomicsengland>
[Facebook]<https://www.facebook.com/genomicsengland>
[YouTube]<https://www.youtube.com/GenomicsEngland>
[LinkedIn]<https://www.linkedin.com/company/genomics-england/>
[Instagram]<https://www.instagram.com/genomicsengland/>

From: Eric Czech ***@***.***>
Date: Friday, 7 June 2024 at 16:09
To: sgkit-dev/vcf-zarr-publication ***@***.***>
Cc: Samuel Tallman ***@***.***>, Mention ***@***.***>
Subject: Re: [sgkit-dev/vcf-zarr-publication] Permission to submit preprint (Issue #145)

CAUTION: This email originated from outside the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.

I give permission to submit

**Comment by stallmanGEL** [comment]
I give permission to submit

**Comment by alimanfoo** [comment]
I give permission to submit

**Comment by shz9** [comment]
I give permission to submit

**Comment by ravwojdyla** [comment]
I give permission to submit

**Comment by benjeffery** [comment]
I give permission to submit

**Comment by jeromekelleher** [comment]
Genomics England have confirmed that the paper has passed their approval process.

**Comment by timothymillar** [comment]
With #149 I can give permission to submit. My Apologies for the delay.

**Comment by jeromekelleher** [comment]
Submitted to Biorxiv :tada: I've attached the submitted version for ease of reference here.

I'll submit to GigaScience when I get back.

[paper.pdf](https://github.com/user-attachments/files/15784334/paper.pdf)

**Comment by hammer** [comment]
Fantastic enjoy your week off Jerome!

**Comment by hammer** [comment]
It's up! https://www.biorxiv.org/content/10.1101/2024.06.11.598241v1

**Comment by jeromekelleher** [comment]
Submitted to gigascience :crossed_fingers: 

I made a few small tweaks covering some omissions, will update the biorxiv version also when I get a chance.
