### ISSUE TITLE
Conflicts of Interest

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#147]
We need to declare any conflicts of interest. Here's what I have at the moment:

> Jerome Kelleher and Ben Jeffery are paid consultants for Genomics England Limited.

Does anyone have anything to add to this?

**Comment by jeromekelleher** [comment]
@hammer - any CoIs to declare here?

**Comment by hammer** [comment]
I don’t think so? I’m on the technical advisory board for Our Future Health, is that something to declare? None of my board seats are relevant, and none of my investments are material

**Comment by jeromekelleher** [comment]
I don't think so either, just making sure.

**Comment by jeromekelleher** [comment]
I'm going to assume no one else has CoIs to declare at this point, we can always update later if needs be.
