### ISSUE TITLE
Add Will Tyler to author list

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#155]
The work that @Will-Tyler has done on adding local alleles support to bio2zarr more than qualifies for authorship. The paper is currently under review, but there'll be no problem adding you to the list when we do revisions.

What should we use for your affiliation?

**Comment by Will-Tyler** [comment]
Thank you for offering to add me as an author!

I think "independent contributor" or "no affiliation" would be accurate. I was not associated with a university or company when I made the contributions.

**Comment by jeromekelleher** [comment]
done
