### ISSUE TITLE
Add Per Unneberg to author list

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#170]
@percyfal is leading the spruce dataset example (#169 )

Can you update with your author details please @percyfal (institution, orcid, publishing name etc)?

**Comment by percyfal** [comment]
Sure:

Per Unneberg 

Department of Cell and Molecular Biology, National Bioinformatics Infrastructure Sweden, Science for Life Laboratory, Uppsala University, Uppsala, Sweden

orcid: 0000-0001-5735-3315

Funding: PU was supported by the Knut and Alice Wallenberg Foundation as part of the National Bioinformatics Infrastructure Sweden at SciLifeLab, grant id KAW 2017.0003.

I'll get back with information on funding related to the cluster that I'm running on.

**Comment by percyfal** [comment]
I see our acknowledgement has changed to

PU was supported by the SciLifeLab & Wallenberg Data Driven Life Science Program, Knut and Alice Wallenberg Foundation (grants: KAW 2020.0239 and KAW 2017.0003), and by the National Bioinformatics Infrastructure Sweden (NBIS) at SciLifeLab

**Comment by percyfal** [comment]
Acknowledgement for computational resources:

“The computations were enabled by resources provided by the National Academic Infrastructure for Supercomputing in Sweden (NAISS), partially funded by the Swedish Research Council through grant agreement no. 2022-06725.”

**Comment by jeromekelleher** [comment]
Would you mind updating the tex in the appropriate places with this info next time you're in the document @percyfal?
