### ISSUE TITLE
Add paragraph(s) to Zarr methods section describing usage and implementations

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#29]
We're missing a paragraph at the end of the Methods Zarr section being concrete about how zarr is used. Should reference various geosciences examples, hopefully being concrete about the scale of datasets being used. We can then say that Zarr is getting traction in biology, referring to various recent papers (#7, #6, #3, #23 - and more?). Should also say that Zarr actually originated as a way to store VCF, and reference various MalariaGEN papers using it.

We probably want another paragraph then clarifying the "spec" status of Zarr, and its implementations.

**Comment by tomwhite** [comment]
Also TensorStore: https://research.google/blog/tensorstore-for-high-performance-scalable-array-storage/?m=1
