### ISSUE TITLE
Mention DivBrowse

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#3]
https://academic.oup.com/gigascience/article/doi/10.1093/gigascience/giad025/7135628

**Comment by hammer** [comment]
Some context for my memory: the authors of DivBrowse spoke with Tim M after his talk in January. They've built on scikit-allel and would like to move to sgkit but are waiting to hear on the stability of our data model. We should highlight the Zarr VCF spec more directly for them, activity in our repo does not indicate instability of our core data model.
