### ISSUE TITLE
Updates to Schematic

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#38]
- Remove sample_cohort (not part of VCF and would just confuse people)
- Remove "numcodecs" - this is Python specific, and we would just have to explain what numcodecs is
- Change dimension separator for Zarr chunks from "." to "/" 

The second one is following the default in Zarr v3, plus the default in bio2zarr. For these large datasets, we probably do want to use a hierarchical storage, otherwise we're approaching a million files in a directory for large datasets.

@timothymillar would you be able to pick this up? I'm sure I can manage if you're busy though.

**Comment by timothymillar** [comment]
I should have time in the next few days.

**Comment by timothymillar** [comment]
> The second one is following the default in Zarr v3, plus the default in bio2zarr. For these large datasets, we probably do want to use a hierarchical storage, otherwise we're approaching a million files in a directory for large datasets.

I don't quite follow this part, are you referring to the directory tree in the figure?

**Comment by jeromekelleher** [comment]
Right, that was confusing and obscure! By default Zarr v3 will use "/" as the dimension separator in [chunk keys](https://zarr-specs.readthedocs.io/en/latest/v3/core/v3.0.html#chunk-key-encoding). This is equivalent to using the [NestedDirectoryStore](https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.NestedDirectoryStore).

I've just changed bio2zarr to do this by default also, because it seems like one of the few changes from v2 to v3 (defaults) that can't be done with a quick metadata update, and it is also very useful to limit the number of files in a directory to the number of chunks in a given dimension. For GeL we have on the order of a million chunks, so it does add it.
