### ISSUE TITLE
GeL notebook and data requirements

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#58]
Here is what we want for the final version of the GeL chr2 analysis notebook.

- We want to save the notebook in the repo and refer to it in the paper, so it should be reasonably formatted and sectioned with some explanatory text.
- All of the data required for the "Case Study" section should be in there, and/or derived from running the notebook. (We don't run the actual conversions in the notebook though, that's too much).
- File sizes etc should be reported using du, otherwise the storage used by directories is ignored (non trivial at this case)
- The data for table 1 should be saved in a format that can be loaded again (i.e., a csv for pandas)?
- The data for field histograms should be saved to file so that we can save to the repo and use to create figures

So, we want one notebook and (I think?) 5 csvs to airlock out of the GeL environment.

For re-encoding to int8 for the top 4 columns, it would probably be simplest to create a schema for vcf2zarr encode with just those 4 and the required ``variant_`` columns and run again. We can get the required numbers from the resulting dataset.  I don't trust Dask to successfully complete here and it would just be a waste of time messing with it.

I guess we can also include the example bcftools query(s?) here, and the Zarr code required to implement them.

ping @benjeffery @stallmanGEL

**Comment by jeromekelleher** [comment]
Hmm, looking again we could probably also truncate PL and GQX using the same rationale. Can we run histograms for those also @benjeffery next time around, and also include in the smaller schema?

**Comment by jeromekelleher** [comment]
Oh yes, another thing - could we use xarray directly rather than sgkit here please for getting the histograms? I don't want to have to explain what sgkit is, and we're not really using anything from it here, right?

**Comment by benjeffery** [comment]
Yep, re-encoding 20 with a modified schema is running, will modify notebook to be xarray.

**Comment by benjeffery** [comment]
For clarity, I've truncated AD, GQ, DP, DPF, PL, GQX.

**Comment by benjeffery** [comment]
Here are the `inspect` CSVs for chr2
[chr2_zarr_inspect.csv](https://github.com/sgkit-dev/vcf-zarr-publication/files/15379081/chr2_zarr_inspect.csv)
[chr2_if_inspect.csv](https://github.com/sgkit-dev/vcf-zarr-publication/files/15379082/chr2_if_inspect.csv)

**Comment by jeromekelleher** [comment]
Closed in various recent PRs
