### ISSUE TITLE
Discuss admix-kit

### ISSUE THREAD

**Issue by hammer** [sgkit-dev/vcf-zarr-publication#6]
Uses dask, zarr, and xarray to do statistical genetics. Even has a similar naming scheme! https://github.com/KangchengHou/admix-kit is the repo, https://www.biorxiv.org/content/10.1101/2023.09.30.560263v1 is the publication.

**Comment by jeromekelleher** [comment]
Great find @hammer, will be useful to cite as evidence of convergence around the same technologies.

**Comment by jeromekelleher** [comment]
This is a slightly tricky one, as it's not clear to me they are really using Zarr. The don't mention it in the paper, and it's only used in the repo to load toy data examples. It's a bit tricky to tease apart though.

Can definitely be cited as example of bio application using xarray and dask though.
