### ISSUE TITLE
More nuanced narrative re row-wise vs columnar

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#65]
We're currently pitching Zarr as a columnar alternative to row-wise VCF encoding for narrative purposes, but the reality is more complex. Need to address this in the introduction. I guess we can say what happened when people tried used using standard columnar approaches (or anything else?) to storing VCF data as a table.

**Comment by hammer** [comment]
One point of nuance here is that n-dimensional arrays (tensors) are a common data type in the AI ecosystem, where Arrow and Parquet are also popular, so there have been various attempts to allow a column in those formats to be a tensor. [Arrow](https://arrow.apache.org/docs/format/Other.html) and [Lance](https://lancedb.github.io/lance/arrays.html) docs have more details. Petastorm also provides a [Unischema](https://petastorm.readthedocs.io/en/latest/api.html#module-petastorm.unischema) data model that includes an NdarrayCodec that allows tensors to be stored alongside other column types, cf. [Generating a dataset](https://petastorm.readthedocs.io/en/latest/readme_include.html#id5).

**Comment by tomwhite** [comment]
We could say that Zarr is "chunked-columnar" since data is stored in chunks and each column is stored separately to others.

**Comment by jeromekelleher** [comment]
Closed in  #100
