### ISSUE TITLE
The Hardware Lottery parallels/reference

### ISSUE THREAD

**Issue by ravwojdyla** [sgkit-dev/vcf-zarr-publication#68]
Mentioned in the [20240415 developer call](https://github.com/sgkit-dev/sgkit/discussions/1214), the [The Hardware Lottery](https://arxiv.org/abs/2009.06489) could be an inspiration, from the abstract (emphasis mine):

> Hardware, systems and algorithms research communities have historically had different incentive structures and fluctuating motivation to engage with each other explicitly. **This historical treatment is odd given that hardware and software have frequently determined which research ideas succeed (and fail).** This essay introduces the term hardware lottery to describe when a research idea wins because it is suited to the available software and hardware and not because the idea is superior to alternative research directions. **Examples from early computer science history illustrate how hardware lotteries can delay research progress by casting successful ideas as failures.** These lessons are particularly salient given the advent of domain specialized hardware which make it increasingly costly to stray off of the beaten path of research ideas. This essay posits that the gains from progress in computing are likely to become even more uneven, with certain research directions moving into the fast-lane while progress on others is further obstructed.

We could draw some parallels to the "hardware lottery": VCF, linux pipe and file oriented bio-informatics made sense at the time particularly in the context of the the data sizes, software and hardware available. But at the moment they could be a limiting factor in what "research ideas succeed (and fail)" along with the pace of research.

FYI @jeromekelleher

**Comment by jeromekelleher** [comment]
I like it, thanks @ravwojdyla - definitely a potential last-paragraph narrative in here. I'll read the paper and have a think about it.
