### ISSUE TITLE
Discuss zarr limitations

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#8]
Good to highlight the places that the data model doesn't work so well. E.g., variable length strings, lots of alleles at a site

**Comment by timothymillar** [comment]
I was going to suggest the inefficiency of storing sparse arrays as dense arrays, but it seems that I missed this [update](https://zarr.dev/blog/release-2-11/). We could investigate how well this works using large pedigree kinship matrices which are usually sparse and should contain many empty chunks.

**Comment by timothymillar** [comment]
@jeromekelleher, is the efficiency of storing large sparce matrices still in scope here considering the focus is now explicitly on VCF? If so, I can start trying to identify/simulate a large pedigree to work from. I'm envisaging a figure showing theoretical and realized storage size in Zarr by chunk size.

**Comment by jeromekelleher** [comment]
I think we're focusing exclusively on VCF for now @timothymillar --- I do want to ship this more tightly focused paper as soon as possible (ideally preprinting by the end of the month). So I think we could keep you analysis for the later sgkit paper?

**Comment by timothymillar** [comment]
Thanks, I figured that was the case. Just wanted to be certain that I wasn't going to hold you up!

**Comment by jeromekelleher** [comment]
Closed in #114
