### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#82]
Biology has some bizarre protocols for paper authorship which places complex semantics on the relative ordering of authors. It is impossible to place a total ordering on the value of each person's contribution, and the least-bad approach (IMO) is to place authors into contribution "bins", within which they are alphabetically ordered.

After some discussion @hammer and I have come up with the following proposal:

We have three authorship bins, First, Middle and Senior.

## First

- Eric Czech (@eric-czech): Data model design,  a lot of the early sgkit work
- Tim Millar (@timothymillar): Data model design (polyploidy) + manuscript contribution
- Tom White (@tomwhite): Data model design, VCF Spec, VCF index code, sgkit VCF parsing code

## Middle

- Ben Jeffery (@benjeffery): Bio2zarr, manuscript
- Alistair Miles (@alimanfoo): Foundations, manuscript
- Sam Tallman (@stallmanGEL):  GEL analysis in manuscript
- Rafal Wojdyla (@ravwojdyla): Data model design
- Shadi Zabad (@shz9): Zarr settings analysis for manuscript on 1KG data

## Senior
- Jeff Hammerbacher (@hammer)
- Jerome Kelleher (@jeromekelleher) (corresponding)

Please remember that this is just a proposal and we're happy to discuss if you think we've got it wrong. Keeping track of what everyone has done is hard, and mistakes do happen...

If you are happy with this ordering, please comment or +1 

Please send me the email address that you would like to use for correspondence also, as I'll need to fill in a bunch of details for everyone when it comes to submission time. I'd also like to start circulating drafts to get feedback on, and hopefully we can iterate to submission quality pretty quickly.

**Comment by jeromekelleher** [comment]
Currently looks like this (note the title is preliminary, see #87)

![Screenshot from 2024-04-26 14-34-10](https://github.com/sgkit-dev/vcf-zarr-publication/assets/2664569/3498086f-668b-4440-b922-5f142a05b8b0)

It would be great if authors could update the document with their affiliation details and correct "publication" name. If you have an ORCID, it would also be very helpful if you could record it here.

**Comment by benjeffery** [comment]
https://orcid.org/0000-0002-1982-6801

**Comment by eric-czech** [comment]
https://orcid.org/0000-0002-4254-4255

**Comment by shz9** [comment]
https://orcid.org/0000-0002-8003-9284

**Comment by hammer** [comment]
https://orcid.org/0000-0001-6596-8563

**Comment by hammer** [comment]
For the purposes of this work I think you can put Related Sciences as my affiliation

**Comment by tomwhite** [comment]
+1

**Comment by timothymillar** [comment]
https://orcid.org/0000-0002-5142-8811

**Comment by alimanfoo** [comment]
https://orcid.org/0000-0001-9018-4680

**Comment by stallmanGEL** [comment]
https://orcid.org/0000-0001-7183-6276

**Comment by ravwojdyla** [comment]
https://orcid.org/0009-0005-0735-7090

**Comment by jeromekelleher** [comment]
@tomwhite am I correct in saying you don't have an ORCID? (Fine if you don't, just checking)

**Comment by tomwhite** [comment]
I don't have an ORCID.
